name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: "Upload to PyPI"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.x"
      - name: "Install dependencies"
        run: "python -m pip install --upgrade poetry"
      - name: "Build and publish"
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: "poetry publish --build --username=$PYPI_USERNAME --password=$PYPI_PASSWORD"
